version: '3.3'
services:
  jenkins_master:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    restart: unless-stopped
    ports: 
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_volume://F/Jenkins/volumes
    networks:
      - jenkins_network
      
  jenkins_slave:
    image: jenkins/inbound-agent
    container_name: slave
    restart: unless-stopped
    environment:
      JENKINS_URL: http://jenkins:8080/
      JENKINS_SECRET: a9a7cd910436280ca15c72940c195dafea05a0584012c544c930d27a840e9b62
      JENKINS_AGENT_NAME: slave
      JENKINS_AGENT_WORKDIR: /home/jenkins/agent
    networks:
      - jenkins_network
 
  prometheus:
    image: mon/prometheus
    ports:
    - '9090:9090'
    volumes:
    - prometheus_data:/monitoring/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention=1d'
    networks:
      - jenkins_network
  
  grafana:
    image: grafana/grafana:5.0.0
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - jenkins_network
      
volumes:
  jenkins_volume:
    external: true
  docker_volume:
    external: true
  gitea_volume:
    external: true
  prometheus_data:
  grafana_data:

networks:
  jenkins_network: